"""few fields add in headoffice_01

Revision ID: 1cb17b6e743d
Revises: 4c0d4ed93000
Create Date: 2023-12-08 13:11:37.643387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1cb17b6e743d'
down_revision: Union[str, None] = '4c0d4ed93000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('HeadOffice', table_name='headoffice')
    op.drop_index('ix_headoffice_id', table_name='headoffice')
    op.drop_table('headoffice')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
   
    op.create_table('headoffice',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('HeadOffice', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('State_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Distric_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Distric_id'], ['distric.id'], name='headoffice_ibfk_3'),
    sa.ForeignKeyConstraint(['Region_id'], ['region.id'], name='headoffice_ibfk_2'),
    sa.ForeignKeyConstraint(['State_id'], ['state.id'], name='headoffice_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_headoffice_id', 'headoffice', ['id'], unique=False)
    op.create_index('HeadOffice', 'headoffice', ['HeadOffice'], unique=False)
   
    # ### end Alembic commands ###
