"""taluka_add_table

Revision ID: 40cee7691a5f
Revises: 72f94b4ab7ec
Create Date: 2023-12-11 17:17:16.278393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40cee7691a5f'
down_revision: Union[str, None] = '72f94b4ab7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass