"""post_modofied

Revision ID: 5d6b1acab239
Revises: 9b9752dd9a0a
Create Date: 2023-12-12 18:22:47.803424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d6b1acab239'
down_revision: Union[str, None] = '9b9752dd9a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('post')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Post', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('State_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Distric_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('HeadOffice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Subdivision_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Taluka_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['Distric_id'], ['distric.id'], name='post_ibfk_3'),
    sa.ForeignKeyConstraint(['HeadOffice_id'], ['headoffice.id'], name='post_ibfk_4'),
    sa.ForeignKeyConstraint(['Region_id'], ['region.id'], name='post_ibfk_2'),
    sa.ForeignKeyConstraint(['State_id'], ['state.id'], name='post_ibfk_1'),
    sa.ForeignKeyConstraint(['Subdivision_id'], ['subdivision.id'], name='post_ibfk_5'),
    sa.ForeignKeyConstraint(['Taluka_id'], ['taluka.id'], name='post_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
  