"""head office table genarated

Revision ID: 815ef71f4ec1
Revises: e1a41eb960c9
Create Date: 2023-12-07 18:33:52.845797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '815ef71f4ec1'
down_revision: Union[str, None] = 'e1a41eb960c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
