"""post_table_created

Revision ID: 9b9752dd9a0a
Revises: f5ea06a19869
Create Date: 2023-12-12 17:40:11.359817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b9752dd9a0a'
down_revision: Union[str, None] = 'f5ea06a19869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
 pass