"""policestation_modify_01

Revision ID: c572a8442519
Revises: 8cd13f538b67
Create Date: 2023-12-12 13:18:51.058962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c572a8442519'
down_revision: Union[str, None] = '8cd13f538b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('ix_policestation_id', table_name='policestation')
    op.drop_table('policestation')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  
    
    
    op.create_table('policestation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('PoliceStation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_policestation_id', 'policestation', ['id'], unique=False)
   