"""policestation_modify_02

Revision ID: f5ea06a19869
Revises: c572a8442519
Create Date: 2023-12-12 14:43:48.250274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5ea06a19869'
down_revision: Union[str, None] = 'c572a8442519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('ix_policestation_id', table_name='policestation')
    op.drop_table('policestation')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('policestation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('PoliceStation', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('State_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Distric_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('HeadOffice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Subdivision_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Taluka_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['Distric_id'], ['distric.id'], name='policestation_ibfk_3'),
    sa.ForeignKeyConstraint(['HeadOffice_id'], ['headoffice.id'], name='policestation_ibfk_4'),
    sa.ForeignKeyConstraint(['Region_id'], ['region.id'], name='policestation_ibfk_2'),
    sa.ForeignKeyConstraint(['State_id'], ['state.id'], name='policestation_ibfk_1'),
    sa.ForeignKeyConstraint(['Subdivision_id'], ['subdivision.id'], name='policestation_ibfk_5'),
    sa.ForeignKeyConstraint(['Taluka_id'], ['taluka.id'], name='policestation_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_policestation_id', 'policestation', ['id'], unique=False)
   